# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: cloudlink-deployment
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: cloudlink
#   template:
#     metadata:
#       labels:
#         app: cloudlink
#     spec:
#       containers:
#         - name: cloudlink
#           image: cloudlink-app
#           imagePullPolicy: Never
#           ports:
#             - containerPort: 8000



apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudlink-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudlink
  template:
    metadata:
      labels:
        app: cloudlink
    spec:
      containers:
        - name: cloudlink
          image: cloudlink-app
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
